var courses =
{classes:
[{"term": "Incoming Credits",
"classList": [
  { "number": "BB1100",
  "name": "Biology Elective",
  "tagClass": "science",
  "tags": "Science"},
  { "number": "CH1010",
  "name": "Molecularity",
  "tagClass": "science",
  "tags": "Science"},
  { "number": "EN1000",
  "name": "English Language & Comp",
  "tagClass": "hua",
  "tags": "HU&A"},
  { "number": "EN1010",
  "name": "English Literature & Comp",
  "tagClass": "hua",
  "tags": "HU&A"},
  { "number": "PSY1400",
  "name": "Intro to Psychological Science",
  "tagClass": "social",
  "tags": "Social Science"},
  { "number": "MA1021",
  "name": "Calculus I",
  "tagClass": "math",
  "tags": "Math"},
  { "number": "MA1022",
  "name": "Calculus II",
  "tagClass": "math",
  "tags": "Math"},
]},
{"term": "Fall 2013",
"classList": [
  { "number": "EN2242",
  "name": "Popular Fiction: Reading in Installments",
  "tagClass": "hua",
  "tags": "HU&A"},
  { "number": "MA1023",
  "name": "Calculus III",
  "tagClass": "math",
  "tags": "Math"},
  { "number": "MA1024",
  "name": "Calculus IV",
  "tagClass": "math",
  "tags": "Math"},
  { "number": "PH1110",
  "name": "General Physics - Mechanics",
  "tagClass": "science",
  "tags": "Science"},
  { "number": "PH1120",
  "name": "General Physics - Elec & Magnetism",
  "tagClass": "science",
  "tags": "Science"},
  { "number": "PSY1401",
  "name": "Cognitive Psychology",
  "tagClass": "social",
  "tags": "Social Science"},
]},
{"term": "Spring 2014",
"classList": [
  { "number": "BB1002",
  "name": "Environmental Biology",
  "tagClass": "science",
  "tags": "Science"},
  { "number": "BB2920",
  "name": "Genetics",
  "tagClass": "science",
  "tags": "Science"},
  { "number": "CH1020",
  "name": "Forces and Bonding",
  "tagClass": "science",
  "tags": "Science"},
  { "number": "CS110X",
  "name": "Intro to Programming",
  "tagClass": "cs",
  "tags": "Computer Science"},
  { "number": "MA2051",
  "name": "Ordinary Differntial Equations",
  "tagClass": "math",
  "tags": "Math"},
]},
{"term": "Fall 2014",
"classList": [
  { "number": "AR2101",
  "name": "3D Modeling I",
  "tagClass": "hua",
  "tags": "HU&A"},
  { "number": "BME2210",
  "name": "Biomdeical Signals, Instruments & Measurements",
  "tagClass": "science",
  "tags": "Science"},
  { "number": "CS2022",
  "name": "Discrete Mathematics",
  "tagClass": "cs",
  "tags": "Computer Science"},
  { "number": "CS2301",
  "name": "Systems Programming",
  "tagClass": "cs",
  "tags": "Computer Science"},
  { "number": "ES3001",
  "name": "Intro to Thermodynamics",
  "tagClass": "science",
  "tags": "Science"},
  { "number": "ES3004",
  "name": "Fluid Mechanics",
  "tagClass": "science",
  "tags": "Science"},
]},
{"term": "Spring 2015",
"classList": [
  { "number": "AR2202",
  "name": "Figure Drawing",
  "tagClass": "hua",
  "tags": "HU&A"},
  { "number": "BME2811",
  "name": "Intro to Biomaterials & Tissue Engineering",
  "tagClass": "science",
  "tags": "Science"},
  { "number": "CS2102",
  "name": "Object-Oriented Design Concepts",
  "tagClass": "cs",
  "tags": "Computer Science"},
  { "number": "CCS3733",
  "name": "Software Engineering",
  "tagClass": "cs",
  "tags": "Computer Science"},
  { "number": "ECE2010",
  "name": "Intro to Electrical & Computer Engineering",
  "tagClass": "science",
  "tags": "Science"},
  { "number": "ISPGTH",
  "name": "Reproducible Research in Computational Science",
  "tagClass": "cs",
  "tags": "Computer Science"},
]},
{"term": "Fall 2015",
"classList": [
  { "number": "AR1101",
  "name": "Digital Imaging",
  "tagClass": "hua",
  "tags": "HU&A"},
  { "number": "CS2223",
  "name": "Algorithms",
  "tagClass": "cs",
  "tags": "Computer Science"},
  { "number": "3013",
  "name": "Operating Systems",
  "tagClass": "cs",
  "tags": "Computer Science"},
  { "number": "CS3431",
  "name": "Database Systems I",
  "tagClass": "cs",
  "tags": "Computer Science"},
  { "number": "CS4241",
  "name": "Webware",
  "tagClass": "cs",
  "tags": "Computer Science"},
  { "number": "MA2621",
  "name": "Probability for Applicaitons",
  "tagClass": "math",
  "tags": "Math"},
]},
{"term": "Spring 2016",
"classList": [
  { "number": "CS3133",
  "name": "Foundations of Computer Science",
  "tagClass": "cs",
  "tags": "Computer Science"},
  { "number": "ID2050",
  "name": "Social Science - IQP Greece",
  "tagClass": "social",
  "tags": "Social Science"},
  { "number": "MA2611",
  "name": "Applied Statistics I",
  "tagClass": "math",
  "tags": "Math"},
  { "number": "IQP",
  "name": "Urban Agriculture in Greece",
  "tagClass": "iqp",
  "tags": "IQP"},
  { "number": "PQP",
  "name": "Urban Agriculture in Greece",
  "tagClass": "iqp",
  "tags": "IQP"},
]},
{"term": "Fall 2016",
"classList": [
  { "number": "CS4341",
  "name": "Intro to Artificial Intelligence",
  "tagClass": "cs",
  "tags": "Computer Science"},
  { "number": "CS4445",
  "name": "Data Mining",
  "tagClass": "cs",
  "tags": "Computer Science"},
  { "number": "ETR1100",
  "name": "Engineering Entrepreneurship",
  "tagClass": "free",
  "tags": "Free Elective"},
  { "number": "HU3900",
  "name": "Inquiry Seminar",
  "tagClass": "hua",
  "tags": "HU&A"},
  { "number": "MQP",
  "name": "Scalable Transaction Analytics (A&B Term)",
  "tagClass": "cs",
  "tags": "Computer Science"},
]}]
}
